name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Deploy
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          set -e
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

          echo "Performing deploy..."
          rsync -avz --delete ./target/release/sylvie "${SSH_USER}@${SSH_HOST}":/home/anon/sylvie/sylvie
          rsync -avz --delete ./translations "${SSH_USER}@${SSH_HOST}":/home/anon/sylvie/

          echo "Launching bot..."
          ssh "${SSH_USER}@${SSH_HOST}" '
            tmux kill-session -t sylv 2>/dev/null || true
            tmux new-session -d -s sylv -c /home/anon/sylvie ./sylvie
          '